"use client";

import ReactMarkdown from "react-markdown";

interface AuditDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  auditReceipt: string;
  riskLevel: string;
  modelUsed: string;
}

export default function AuditDrawer({
  isOpen,
  onClose,
  auditReceipt,
  riskLevel,
  modelUsed,
}: AuditDrawerProps) {
  if (!isOpen) return null;

  const riskColor =
    riskLevel === "HIGH" ? "var(--danger)" :
    riskLevel === "MEDIUM" ? "var(--warning)" : "var(--success)";

  const handleDownloadPdf = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    // Convert markdown to a simple HTML string for printing
    // We'll render the markdown content into the print window
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Sentinel Audit Receipt</title>
          <style>
            body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; color: #111; line-height: 1.6; }
            h1, h2, h3 { color: #1a1a2e; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
            strong { color: #1a1a2e; }
            code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
            pre { background: #f4f4f4; padding: 12px; border-radius: 6px; overflow-x: auto; }
            ul, ol { padding-left: 20px; }
            .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; }
            .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold;
              background: ${riskLevel === "HIGH" ? "#fee2e2" : riskLevel === "MEDIUM" ? "#fef3c7" : "#dcfce7"};
              color: ${riskLevel === "HIGH" ? "#dc2626" : riskLevel === "MEDIUM" ? "#d97706" : "#16a34a"}; }
            .meta { font-size: 12px; color: #666; margin-bottom: 32px; }
            .footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1 style="border:none;margin:0">🛡️ Sentinel Audit Receipt</h1>
            <span class="badge">${riskLevel} RISK</span>
          </div>
          <div class="meta">
            Model: ${modelUsed === "fair" ? "Fair (Reweighed)" : "Biased (Raw)"} &nbsp;·&nbsp;
            Generated by Gemini 2.5 Flash &nbsp;·&nbsp;
            ${new Date().toLocaleString()}
          </div>
          <div id="content"></div>
          <div class="footer">This audit receipt was auto-generated for compliance documentation purposes. Sentinel AI Governance Platform.</div>
          <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
          <script>
            document.getElementById('content').innerHTML = marked.parse(${JSON.stringify(auditReceipt)});
            window.onload = () => { window.print(); window.close(); };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/60 backdrop-blur-sm z-40"
        onClick={onClose}
      />

      {/* Drawer */}
      <div className="fixed top-0 right-0 h-full w-full max-w-lg z-50 animate-slide-in-right">
        <div className="h-full bg-card border-l border-card-border flex flex-col">
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-card-border">
            <div>
              <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
                </svg>
                Audit Receipt
              </h2>
              <p className="text-xs text-muted mt-1">Generated by Gemini 2.5 Flash</p>
            </div>
            <div className="flex items-center gap-3">
              <span
                className="text-xs font-bold px-3 py-1 rounded-full"
                style={{ background: riskColor + "22", color: riskColor }}
              >
                {riskLevel} RISK
              </span>
              <button
                onClick={handleDownloadPdf}
                title="Download as PDF"
                className="p-2 rounded-lg hover:bg-white/5 transition-colors text-muted hover:text-foreground cursor-pointer"
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
                  <polyline points="7 10 12 15 17 10" />
                  <line x1="12" y1="15" x2="12" y2="3" />
                </svg>
              </button>
              <button
                id="close-audit-drawer"
                onClick={onClose}
                className="p-2 rounded-lg hover:bg-white/5 transition-colors text-muted hover:text-foreground cursor-pointer"
              >
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18" />
                  <line x1="6" y1="6" x2="18" y2="18" />
                </svg>
              </button>
            </div>
          </div>

          {/* Model badge */}
          <div className="px-6 pt-4">
            <span className="text-xs px-3 py-1 rounded-full bg-accent/10 text-accent font-medium">
              Model: {modelUsed === "fair" ? "Fair (Reweighed)" : "Biased (Raw)"}
            </span>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto p-6">
            <div className="prose prose-invert prose-sm max-w-none
              [&_h1]:text-foreground [&_h1]:text-base [&_h1]:font-bold [&_h1]:mb-3 [&_h1]:mt-5
              [&_h2]:text-foreground [&_h2]:text-sm [&_h2]:font-semibold [&_h2]:mb-2 [&_h2]:mt-4
              [&_h3]:text-muted [&_h3]:text-xs [&_h3]:font-semibold [&_h3]:uppercase [&_h3]:tracking-wider [&_h3]:mb-2 [&_h3]:mt-4
              [&_p]:text-gray-300 [&_p]:text-sm [&_p]:leading-relaxed [&_p]:mb-3
              [&_strong]:text-foreground [&_strong]:font-semibold
              [&_ul]:text-gray-300 [&_ul]:text-sm [&_ul]:pl-4 [&_ul]:mb-3 [&_ul]:space-y-1
              [&_ol]:text-gray-300 [&_ol]:text-sm [&_ol]:pl-4 [&_ol]:mb-3 [&_ol]:space-y-1
              [&_li]:leading-relaxed
              [&_code]:bg-white/5 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-xs [&_code]:text-accent
              [&_hr]:border-card-border [&_hr]:my-4">
              <ReactMarkdown>{auditReceipt}</ReactMarkdown>
            </div>
          </div>

          {/* Footer */}
          <div className="p-6 border-t border-card-border">
            <p className="text-xs text-muted text-center">
              Auto-generated for compliance documentation purposes.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
