"use client";

interface AuditDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  auditReceipt: string;
  riskLevel: string;
  modelUsed: string;
}

export default function AuditDrawer({
  isOpen,
  onClose,
  auditReceipt,
  riskLevel,
  modelUsed,
}: AuditDrawerProps) {
  if (!isOpen) return null;

  const riskColor =
    riskLevel === "HIGH" ? "var(--danger)" :
    riskLevel === "MEDIUM" ? "var(--warning)" : "var(--success)";

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/60 backdrop-blur-sm z-40"
        onClick={onClose}
      />

      {/* Drawer */}
      <div className="fixed top-0 right-0 h-full w-full max-w-lg z-50 animate-slide-in-right">
        <div className="h-full bg-card border-l border-card-border flex flex-col">
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-card-border">
            <div>
              <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
                </svg>
                Audit Receipt
              </h2>
              <p className="text-xs text-muted mt-1">
                Generated by Gemini 2.5 Flash
              </p>
            </div>
            <div className="flex items-center gap-3">
              <span
                className="text-xs font-bold px-3 py-1 rounded-full"
                style={{ background: riskColor + "22", color: riskColor }}
              >
                {riskLevel} RISK
              </span>
              <button
                id="close-audit-drawer"
                onClick={onClose}
                className="p-2 rounded-lg hover:bg-white/5 transition-colors text-muted hover:text-foreground cursor-pointer"
              >
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18" />
                  <line x1="6" y1="6" x2="18" y2="18" />
                </svg>
              </button>
            </div>
          </div>

          {/* Model badge */}
          <div className="px-6 pt-4">
            <span className="text-xs px-3 py-1 rounded-full bg-accent/10 text-accent font-medium">
              Model: {modelUsed === "fair" ? "Fair (Reweighed)" : "Biased (Raw)"}
            </span>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto p-6">
            <div className="prose prose-invert prose-sm max-w-none text-sm leading-relaxed text-gray-300 whitespace-pre-wrap">
              {auditReceipt}
            </div>
          </div>

          {/* Footer */}
          <div className="p-6 border-t border-card-border">
            <p className="text-xs text-muted text-center">
              This audit receipt was auto-generated for compliance documentation purposes.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
